[package]
name = "hue_storage"
version = "0.1.0"
authors = ["Joost Yervante Damad <joost@damad.be>"]
license = "MIT/Apache-2.0"

[dependencies.philipshue]
version = "0.0"
features = ["ssdp","unstable"]
default-features = false

[dependencies]
ssdp = "0.3"
serde_derive = "0.8"
serde = "0.8"
serde_json = "0.8"
