[package]
name = "hue_persistence"
version = "0.1.2"
authors = ["Joost Yervante Damad <joost@damad.be>"]
license = "MIT/Apache-2.0"
description = "Hue persistence for Philips Hue lights"
documentation = "https://github.com/andete/hue_persistence"
homepage = "https://github.com/andete/hue_persistence"
repository = "https://github.com/andete/hue_persistence"
readme = "README.md"
keywords = ["philips","hue","light","bulb","automation"]

[dependencies.philipshue]
version = "0.0"
features = ["ssdp","unstable"]
default-features = false

[dependencies]
ssdp = "0.3"
serde_derive = "0.8"
serde = "0.8"
serde_json = "0.8"
syslog = "3.2"
log = "0.3"
