[package]
name = "hue_storage"
version = "0.1.0"
authors = ["Joost Yervante Damad <joost@damad.be>"]
license = "MIT/Apache-2.0"

[dependencies.philips_hue_client]
version = "0.4"
features = ["ssdp","nightly"]
default-features = false
